ALTER TABLE PAYMENT_EXECUTION.PAYMENTTRANSACTION
    ADD COLUMN IF NOT EXISTS
    OrganisationId UUID;

UPDATE PAYMENT_EXECUTION.PAYMENTTRANSACTION
    SET OrganisationId='00000000-0000-0000-0000-000000000000'
    WHERE OrganisationId is NULL;

ALTER TABLE PAYMENT_EXECUTION.PAYMENTTRANSACTION
    ALTER COLUMN OrganisationId SET NOT NULL;