// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace A2APaymentsApp.Migrations
{
    [DbContext(typeof(UserContext))]
    partial class UserContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("A2APaymentsApp.Models.Organisation", b =>
                {
                    b.Property<string>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountIdForPayment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BankAccountNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantShortCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TenantId");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("A2APaymentsApp.Models.SignUpWithXeroUser", b =>
                {
                    b.Property<string>("XeroUserId")
                        .HasColumnType("TEXT")
                        .HasColumnName("XeroUserId");

                    b.Property<DateTime>("AccountCreatedDateTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthEventId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConnectionCreatedDateUtc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GivenName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubscriptionPlan")
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantCountryCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TenantShortCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("XeroUserId");

                    b.ToTable("SignUpWithXeroUsers", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
