---
Version: "2012-10-17"
Statement:
  - Effect: Allow
    Action:
      - secretsmanager:Get*
    Resource:
      - arn:aws:secretsmanager:${region}:${aws_account_id}:secret:${connection_string_secret_name}-??????
      - arn:aws:secretsmanager:${region}:${aws_account_id}:secret:${retool_user_password_secret_name}-??????
      - arn:aws:secretsmanager:${region}:${aws_account_id}:secret:${schema_manager_password_secret_name}-??????
  - Effect: Allow
    Action:
      - kms:Encrypt
      - kms:Decrypt
      - kms:ReEncrypt*
      - kms:GenerateDataKey*
      - kms:DescribeKey
      - kms:ListAliases
    Resource: ${db_secret_kms_key_arn}
