openapi: 3.1.0
info:
  title: Payment Execution Database
  description: Datastore to persist payment transaction
  x-cortex-tag: svZ2goYQnrGkthqfsaUeBb
  x-cortex-git:
    github:
      alias: ghec-xero-internal
      repository: xero-internal/payment-execution-service
      basepath: projects/database
  x-cortex-type: service
  x-cortex-slack:
    channels:
    - name: pod-cashtopia
  x-cortex-owners:
    - name: KWoKzMn5LkuWsnyjjGo0yw
      type: GROUP
      provider: CORTEX
  x-cortex-parents:
    - tag: 49xwsKimDUdmnG3H6riNhB
  x-cortex-groups:
  - phase:sustained-release
  - data-sensitivity-level:sensitive
  - personal-data-indicator:personal
  - type:datastore
  x-cortex-static-analysis:
    sonarqube:
      project: xero-internal_payment-execution-service
      alias: sqc-xero-internal-prod
  x-cortex-issues:
    jira:
      projects:
        - name: INPAY


